# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea65863b7c2754cbb9a21f612eb5cc41b5549c9a01cab91ef8e22f10989f233a54614e5c22b24cd12f8b6e32a167d9591c8c3924950b560269e13786d2c89fcd

test:
  secret_key_base: 81499333d57bc3916b1ab7262c826d412658a92be9d70c6c65c1841561d5976a61a0a88bf7f4aacf4fb2c68ec4d6c0bcc5744bf2c2a2d4fbecf264278bd6d2b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
